/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasimanajementugas;

import com.sun.glass.events.KeyEvent;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import koneksi.koneksi;

/**
 *
 * @author Ghassan
 */
public class Login extends javax.swing.JFrame {
Connection conn = null;
PreparedStatement pst = null;
ResultSet  rs = null;

private String user = null;

private int x;
private int y;


/**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        loginSignUp = new javax.swing.JLayeredPane();
        pLogin = new javax.swing.JPanel();
        fLoginUsername = new javax.swing.JTextField();
        fLoginPassword = new javax.swing.JPasswordField();
        lCreateAccount = new javax.swing.JLabel();
        bLogin = new javax.swing.JLabel();
        bgLogin = new javax.swing.JLabel();
        pSignUp = new javax.swing.JPanel();
        signupUsername = new javax.swing.JTextField();
        signupFullname = new javax.swing.JTextField();
        signupPassword = new javax.swing.JPasswordField();
        signupPasswordConfirm = new javax.swing.JPasswordField();
        daftar = new javax.swing.JLabel();
        backToLogin = new javax.swing.JLabel();
        bgSignUp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        loginSignUp.setLayout(new java.awt.CardLayout());

        pLogin.setOpaque(false);
        pLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fLoginUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fLoginUsername.setBorder(null);
        fLoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fLoginUsernameActionPerformed(evt);
            }
        });
        fLoginUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fLoginUsernameKeyPressed(evt);
            }
        });
        pLogin.add(fLoginUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 250, 20));

        fLoginPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fLoginPassword.setBorder(null);
        fLoginPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fLoginPasswordKeyPressed(evt);
            }
        });
        pLogin.add(fLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 250, 20));

        lCreateAccount.setForeground(new java.awt.Color(102, 102, 102));
        lCreateAccount.setText("Create an account");
        lCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lCreateAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCreateAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lCreateAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lCreateAccountMouseExited(evt);
            }
        });
        pLogin.add(lCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        bLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLoginMouseClicked(evt);
            }
        });
        pLogin.add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 130, 40));

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasimanajementugas/image/Ilogin.png"))); // NOI18N
        bgLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgLoginMouseDragged(evt);
            }
        });
        bgLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgLoginMousePressed(evt);
            }
        });
        pLogin.add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginSignUp.add(pLogin, "card2");

        pSignUp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signupUsername.setBorder(null);
        signupUsername.setOpaque(false);
        pSignUp.add(signupUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, 30));

        signupFullname.setBorder(null);
        signupFullname.setOpaque(false);
        pSignUp.add(signupFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 250, 20));

        signupPassword.setBorder(null);
        signupPassword.setOpaque(false);
        pSignUp.add(signupPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 250, 20));

        signupPasswordConfirm.setBorder(null);
        signupPasswordConfirm.setOpaque(false);
        pSignUp.add(signupPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 250, 20));

        daftar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarMouseClicked(evt);
            }
        });
        daftar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                daftarKeyPressed(evt);
            }
        });
        pSignUp.add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 150, 40));

        backToLogin.setForeground(new java.awt.Color(255, 255, 255));
        backToLogin.setText("< Back to login");
        backToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToLoginMouseClicked(evt);
            }
        });
        pSignUp.add(backToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        bgSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasimanajementugas/image/sign-up.png"))); // NOI18N
        bgSignUp.setToolTipText("");
        bgSignUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgSignUpMouseDragged(evt);
            }
        });
        bgSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgSignUpMousePressed(evt);
            }
        });
        pSignUp.add(bgSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        loginSignUp.add(pSignUp, "card3");

        getContentPane().add(loginSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fLoginUsernameActionPerformed

    private void fLoginUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fLoginUsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
                cekLogin();

        
        }
    }//GEN-LAST:event_fLoginUsernameKeyPressed

    private void bgLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgLoginMousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_bgLoginMousePressed

    private void bgLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgLoginMouseDragged
        // TODO add your handling code here:
          int mousex = evt.getXOnScreen();
        int mousey = evt.getYOnScreen();
        
        this.setLocation(mousex - x, mousey - y);
    }//GEN-LAST:event_bgLoginMouseDragged

    private void lCreateAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCreateAccountMouseEntered
        // TODO add your handling code here:
        lCreateAccount.setForeground(new java.awt.Color(0,102,255));
    }//GEN-LAST:event_lCreateAccountMouseEntered

    private void lCreateAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCreateAccountMouseExited
        // TODO add your handling code here:
                lCreateAccount.setForeground(new java.awt.Color(102,102,102));
    }//GEN-LAST:event_lCreateAccountMouseExited

    private void fLoginPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fLoginPasswordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
        cekLogin();
        }
    }//GEN-LAST:event_fLoginPasswordKeyPressed

    
    private void cekLogin (){
        conn = koneksi.connect();
        String sql = "Select * from users where username=?";
        try {
            pst =conn.prepareStatement(sql);
            pst.setString(1,fLoginUsername.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                sql = "Select * from users where username=? and password=?";
                pst = conn.prepareStatement(sql); 
                pst.setString(1,rs.getString(1));
                pst.setString(2,fLoginPassword.getText());
                rs = pst.executeQuery();
                if (rs.next())
                {
                 JOptionPane.showMessageDialog(null, "Selamat Datang " + rs.getString(1));
                 new MainMenu(rs.getString(1)).setVisible(true);
//               m.setCurrUser(fLoginUsername.getText().toString());
                dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Password salah");
                }
            } else{
                int response = JOptionPane.showConfirmDialog(null, "BUAT AKUN ?","AKUN TIDAK DITEMUKAN", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
            if (response == 0){
                gantiPanelLogSign(pSignUp);
             }else{
            }
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,"login error : "+ e);
        }
    }
    
    private void bLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLoginMouseClicked
        // TODO add your handling code here:
                cekLogin();
    }//GEN-LAST:event_bLoginMouseClicked

    private void lCreateAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCreateAccountMouseClicked
        // TODO add your handling code here:
        gantiPanelLogSign(pSignUp);
    }//GEN-LAST:event_lCreateAccountMouseClicked

    private void backToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginMouseClicked
        // TODO add your handling code here:
        gantiPanelLogSign(pLogin);
    }//GEN-LAST:event_backToLoginMouseClicked

    private void bgSignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgSignUpMousePressed
        // TODO add your handling code here:
         x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_bgSignUpMousePressed

    private void bgSignUpMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgSignUpMouseDragged
        // TODO add your handling code here:
          int mousex = evt.getXOnScreen();
        int mousey = evt.getYOnScreen();
        
        this.setLocation(mousex - x, mousey - y);
    }//GEN-LAST:event_bgSignUpMouseDragged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void daftarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_daftarKeyPressed
        // TODO add your handling code here:
              
    }//GEN-LAST:event_daftarKeyPressed

    private void daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarMouseClicked
        // TODO add your handling code here:
        
        
        if (signupPassword.getText().equals(signupPasswordConfirm.getText())){
        conn = koneksi.connect();
        String sql = "Select username from users where username=?";
        try {
            pst =conn.prepareStatement(sql);
            pst.setString(1,signupUsername.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "User Sudah Ada :(");
             System.out.println("error");
            }
            else{
                
            String q =  "Insert into users (username, password, nama_lengkap) Values "
                    + "('"+signupUsername.getText()+"', "
                    + "'"+signupPassword.getText()+"', "
                    + "'"+signupFullname.getText()+"');";
            try {
            java.sql.Statement stat = conn.createStatement();
            stat.execute(q); 
            JOptionPane.showMessageDialog(null, "User ditambah");
             System.out.println("nambah");
            } 
            catch (Exception e){
                System.out.println("error" + e);
            }
                
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null,"error "+ e);
         System.out.println("error" + e);
         }
        } else {
                        JOptionPane.showMessageDialog(null,"PASSWORD TIDAK SAMA");
        }
    }//GEN-LAST:event_daftarMouseClicked
    
     private void gantiPanelLogSign(JPanel panel){
        loginSignUp.removeAll();
        loginSignUp.add(panel);
        loginSignUp.repaint();
        loginSignUp.revalidate();
        
        
       
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bLogin;
    private javax.swing.JLabel backToLogin;
    private javax.swing.JLabel bgLogin;
    private javax.swing.JLabel bgSignUp;
    private javax.swing.JLabel daftar;
    private javax.swing.JPasswordField fLoginPassword;
    private javax.swing.JTextField fLoginUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lCreateAccount;
    private javax.swing.JLayeredPane loginSignUp;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pSignUp;
    private javax.swing.JTextField signupFullname;
    private javax.swing.JPasswordField signupPassword;
    private javax.swing.JPasswordField signupPasswordConfirm;
    private javax.swing.JTextField signupUsername;
    // End of variables declaration//GEN-END:variables
}
