/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasimanajementugas;
import aplikasimanajementugas.MainMenu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import koneksi.koneksi;
/**
 *
 * @author Ghassan
 */
public class Setting extends javax.swing.JFrame {
    private String currUser;
  
    Connection conn;

    /**
     * Creates new form Setting
     */
    public Setting(String cUser) {
        currUser = cUser;
        this.conn = new koneksi().connect();
        initComponents();
        getUserSet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sSave = new javax.swing.JLabel();
        sFullName = new javax.swing.JTextField();
        sUsername = new javax.swing.JTextField();
        sOldPass = new javax.swing.JPasswordField();
        sOldPassConfirm = new javax.swing.JPasswordField();
        sNewPass = new javax.swing.JPasswordField();
        exitSet = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sSaveMouseClicked(evt);
            }
        });
        getContentPane().add(sSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 170, 40));

        sFullName.setBorder(null);
        sFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sFullName.setOpaque(false);
        getContentPane().add(sFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 250, 30));

        sUsername.setBorder(null);
        sUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sUsername.setOpaque(false);
        getContentPane().add(sUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 250, 30));

        sOldPass.setBorder(null);
        sOldPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sOldPass.setOpaque(false);
        getContentPane().add(sOldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 250, 30));

        sOldPassConfirm.setBorder(null);
        sOldPassConfirm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sOldPassConfirm.setOpaque(false);
        getContentPane().add(sOldPassConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 250, 30));

        sNewPass.setBorder(null);
        sNewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        sNewPass.setOpaque(false);
        sNewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNewPassActionPerformed(evt);
            }
        });
        getContentPane().add(sNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 480, 250, 30));

        exitSet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitSet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitSetMousePressed(evt);
            }
        });
        getContentPane().add(exitSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 20, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasimanajementugas/image/setting.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitSetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitSetMousePressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitSetMousePressed

    private void sNewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNewPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNewPassActionPerformed

    private void sSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sSaveMouseClicked
        // TODO add your handling code here:
        //Buat update dan cek password lama dengan yang baru serta setting lainnya
        
        JOptionPane.showMessageDialog(null, "Fitur masih dikembangkan");
    }//GEN-LAST:event_sSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Setting().setVisible(true);
            }
        });
    }

    
    public void getUserSet(){
    String sql = "select username, password, nama_lengkap "
            + "from users "
            + "where username ='"+currUser+"';";
        System.out.println(currUser);
    try {
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){    
        sUsername.setText(hasil.getString("username"));
            sFullName.setText(hasil.getString("nama_lengkap"));
            sOldPass.setText(hasil.getString("password"));
            sOldPassConfirm.setText(hasil.getString("password"));
            sNewPass.setText(hasil.getString("password"));
        }
        }
    catch (Exception e){
        System.out.println(e);
    }
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitSet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField sFullName;
    private javax.swing.JPasswordField sNewPass;
    private javax.swing.JPasswordField sOldPass;
    private javax.swing.JPasswordField sOldPassConfirm;
    private javax.swing.JLabel sSave;
    private javax.swing.JTextField sUsername;
    // End of variables declaration//GEN-END:variables
}
